version: '3'
services:
  homeassistant:
    container_name: modern-forms-home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - .config:/config
      - ./custom_components:/config/custom_components
    environment:
      - TZ
    ports:
      - 8223:8123
    networks:
      - modern-forms-home-assistant
    restart: always

networks: 
  modern-forms-home-assistant:
    name: modern-forms-home-assistant
    driver: bridge